backend:
  name: github
  repo: kbaig/alexander-golob

media_folder: static/assets
public_folder: assets

collections:
  - name: uniquePages
    label: Unique Pages
    delete: false
    files:
      - label: Home
        name: home
        file: src/pages/index.md
        fields:
          - { name: title, label: Title, widget: string, required: false }
          - {
              name: description,
              label: Description,
              widget: string,
              required: false,
            }
          - {
              name: ogImage,
              label: Social Image,
              widget: image,
              required: false,
            }
          - name: carouselImages
            label: Carousel Image
            widget: list
            fields:
              - { name: image, label: Image, widget: image }
              - { name: description, label: Description, widget: string }
              - name: link
                label: Link
                widget: object
                fields:
                  - { name: external, label: External, widget: boolean }
                  - { name: path, label: Path, widget: string }
          - { name: heroStatement, label: Hero Statement, widget: string }
          - name: CTAs
            label: CTAs
            widget: object
            fields:
              - name: leftCTA
                label: Left CTA
                widget: object
                fields:
                  - { name: content, label: content, widget: string }
                  - { name: external, label: External, widget: boolean }
                  - { name: path, label: Path, widget: string }
              - name: rightCTA
                label: Right CTA
                widget: object
                fields:
                  - { name: content, label: content, widget: string }
                  - { name: external, label: External, widget: boolean }
                  - { name: path, label: Path, widget: string }
              - name: offCenterCTA
                label: Off Center CTA
                widget: object
                fields:
                  - { name: content, label: content, widget: string }
                  - { name: external, label: External, widget: boolean }
                  - { name: path, label: Path, widget: string }

      - label: About
        name: about
        file: src/pages/about.md
        fields:
          - { name: title, label: Title, widget: string, required: false }
          - {
              name: description,
              label: Description,
              widget: string,
              required: false,
            }
          - {
              name: ogImage,
              label: Social Image,
              required: false,
              widget: image,
            }
          - { name: heading, label: Heading, widget: string }
          - name: links
            Label: Links
            widget: list
            fields:
              - { name: content, label: Content, widget: string }
              - { name: path, label: Path, widget: string }
          - name: companyDescription
            label: Company Description
            widget: object
            fields:
              - { name: heading, label: Heading, widget: string }
              - { name: md_content, label: Content, widget: markdown }
          - name: teamSection
            label: Team Section
            widget: list
            fields:
              - { name: heading, label: Heading, widget: string }
              - name: CVLink
                label: CV Link
                widget: object
                fields:
                  - { name: show, label: Show, widget: boolean, default: false }
                  - { name: content, label: Content, widget: string }
                  - { name: external, label: External, widget: boolean }
                  - { name: path, label: Path, widget: string }
              - { name: image, label: Image, widget: image }
              - { name: contentHeading, label: Content Heading, widget: string }
              - { name: md_content, label: Content, widget: markdown }

      - label: Portfolio
        name: portfolio
        file: src/pages/portfolio.md
        fields:
          - { name: title, label: Title, widget: string, required: false }
          - {
              name: description,
              label: Description,
              widget: string,
              required: false,
            }
          - {
              name: ogImage,
              label: Social Image,
              required: false,
              widget: image,
            }
          - { name: heading, label: Heading, widget: string }

      - label: Blog
        name: blog
        file: src/pages/blog.md
        fields:
          - { name: title, label: Title, widget: string, required: false }
          - {
              name: description,
              label: Description,
              widget: string,
              required: false,
            }
          - {
              name: ogImage,
              label: Social Image,
              required: false,
              widget: image,
            }
          - { name: heading, label: Heading, widget: string }
          - name: links
            Label: Links
            widget: list
            fields:
              - { name: content, label: Content, widget: string }
              - { name: path, label: Path, widget: string }

      - label: Tags
        name: tags
        file: src/pages/tags.md
        fields:
          - { name: title, label: Title, widget: string, required: false }
          - {
              name: description,
              label: Description,
              widget: string,
              required: false,
            }
          - {
              name: ogImage,
              label: Social Image,
              required: false,
              widget: image,
            }

      - label: CV
        name: cv
        file: src/pages/cv.md
        fields:
          - { name: title, label: Title, widget: string, required: false }
          - {
              name: description,
              label: Description,
              widget: string,
              required: false,
            }
          - {
              name: ogImage,
              label: Social Image,
              required: false,
              widget: image,
            }
          - { name: heading, label: Heading, widget: string }
          - name: links
            Label: Links
            widget: list
            fields:
              - { name: content, label: Content, widget: string }
              - { name: path, label: Path, widget: string }
          - name: CVButton
            label: CV Button
            widget: object
            fields:
              - { name: content, label: Content, widget: string }
              - {
                  name: filename,
                  label: File,
                  widget: file,
                  allow_multiple: false,
                }
          - name: CV
            label: CV
            widget: object
            fields:
              - { name: title, label: Title, widget: string }
              - { name: name, label: Name, widget: string }
              - name: personalDetails
                label: Personal Details
                widget: list
                field: { name: detail, label: Detail, widget: string }
              - { name: image, label: Image, widget: image }
              - name: sections
                label: Sections
                widget: list
                fields:
                  - { name: title, label: Title, widget: string }
                  - name: items
                    label: Items
                    widget: list
                    fields:
                      - { name: year, label: Year, widget: string }
                      - name: bulletPoints
                        label: Bullet Points
                        widget: list
                        field:
                          {
                            name: bulletPoint,
                            label: Bullet Point,
                            widget: string,
                          }

      - label: Contact
        name: contact
        file: src/pages/contact.md
        fields:
          - { name: title, label: Title, widget: string, required: false }
          - {
              name: description,
              label: Description,
              widget: string,
              required: false,
            }
          - {
              name: ogImage,
              label: Social Image,
              required: false,
              widget: image,
            }
          - { name: heading, label: Heading, widget: string }
          - name: links
            Label: Links
            widget: list
            fields:
              - { name: content, label: Content, widget: string }
              - { name: path, label: Path, widget: string }
          - { name: statement, label: Statement, widget: string }
          - { name: image, label: Image, widget: image }

      - label: Subscribe
        name: subscribe
        file: src/pages/subscribe.md
        fields:
          - { name: title, label: Title, widget: string, required: false }
          - {
              name: description,
              label: Description,
              widget: string,
              required: false,
            }
          - {
              name: ogImage,
              label: Social Image,
              required: false,
              widget: image,
            }
          - { name: heading, label: Heading, widget: string }
          - name: links
            Label: Links
            widget: list
            fields:
              - { name: content, label: Content, widget: string }
              - { name: path, label: Path, widget: string }
          - { name: statement, label: Statement, widget: string }
          - { name: image, label: Image, widget: image }

      - label: '404'
        name: '404'
        file: src/pages/404.md
        fields:
          - { name: title, label: Title, widget: string, required: false }
          - {
              name: description,
              label: Description,
              widget: string,
              required: false,
            }
          - {
              name: ogImage,
              label: Social Image,
              required: false,
              widget: image,
            }
          - { name: message, label: Message, widget: string }
          - { name: subtitle, label: Subtitle, widget: string }
          - { name: preImage, label: Pre Image Statement, widget: string }
          - { name: image, label: Image, widget: image }
          - { name: preLink, label: Pre Link Statement, widget: string }
          - { name: preContact, label: Pre Contact Statement, widget: string }

  - name: blog
    label: Blog
    folder: src/pages/blog
    fields:
      - { name: templateKey, widget: hidden, default: blog-post }
      - { name: title, label: Title, widget: string, required: true }
      - { name: subtitle, label: Subtitle, widget: string }
      - {
          name: description,
          label: Description,
          widget: string,
          required: false,
        }
      - { name: ogImage, label: Social Image, required: false, widget: image }
      - { name: date, label: Date, widget: date }
      - { name: headerImage, label: Header Image, widget: image }
      - { name: author, label: Author, widget: string }
      - { name: path, label: Path, widget: string }
      - { name: tags, label: Tags, widget: list }
      - { name: body, label: body, widget: markdown }

  - name: siteSettings
    label: Site Settings
    delete: false
    files:
      - name: logo
        label: Logo
        file: src/site-settings/logo.md
        fields:
          - { name: logo, label: Logo, widget: image }

      - name: SEO
        label: SEO
        file: src/site-settings/SEO.md
        fields:
          - { name: siteTitle, label: Site Title, widget: string }
          - { name: siteDescription, label: Site Description, widget: string }
  # - name: sharedComponents
  #   label: Shared Components
  #   delete: false
  #   files:
  #     - name:
  # - name: projectCategories
  #   label: Project Categories
  #   folder: src/pages/project-categories
  #   fields:
  #     - { name: templateKey, widget: hidden, default: project-category }
  #     - { name: title, label: Title, widget: string }
  #     - name: subheadings
  #       label: Subheading
  #       widget: object
  #       fields:
  #         - { name: subheading1, label: Subheading 1, widget: string }
  #         - { name: subheading2, label: Subheading 2, widget: string }
  #         - { name: subheading3, label: Subheading 3, widget: string }
  #         - { name: subheading4, label: Subheading 4, widget: string }
  #     - name: descriptions
  #       label: Descriptions
  #       widget: object
  #       fields:
  #         - name: description1
  #           label: Description 1
  #           widget: object
  #           fields:
  #             - { name: heading, label: Heading, widget: string }
  #             - { name: content, label: Content, widget: markdown }
  #             - { name: image, label: Image, widget: image }
  #         - name: description2
  #           label: Description 2
  #           widget: object
  #           fields:
  #             - { name: heading, label: Heading, widget: string }
  #             - { name: content, label: Content, widget: markdown }
  #             - { name: image, label: Image, widget: image }
  #         - name: description3
  #           label: Description 3
  #           widget: object
  #           fields:
  #             - { name: heading, label: Heading, widget: string }
  #             - { name: content, label: Content, widget: markdown }
  #             - { name: image, label: Image, widget: image }
  # - name: project-subcategories
  #   label: Project Subcategories
  #   folder: src/pages/project-subcategories
  #   create: true
  #   delete: true
  #   fields:
  #     - { name: templateKey, widget: hidden, default: project-subcategory }
  #     - { name: title, label: Title, widget: string }
  #     - name: category
  #       label: Category
  #       widget: select
  #       options:
  #         - { label: Art, value: art }
  #         - { label: Engagements, value: engagements }
  #         - { label: Consulting, value: consulting }
  #         - { label: Special Projects, value: specialProjects }
  #     - { name: body, label: Description Body, widget: markdown }
  #     - name: cta
  #       label: CTA
  #       widget: object
  #       fields:
  #         - { name: statementAbove, label: Statement Above CTA, widget: string }
  #         - { name: statement, label: CTA Statement, widget: string }
  #         - { name: path, label: Path, widget: string }
  # - name: settings
  #   label: Site Settings
  #   files:
  #     - name: left-nav
  #       label: Left Navigation Bar
  #       file: src/settings/left-nav.md
  #       fields:
  #         - name: key
  #           label: key
  #           widget: hidden
  #           default: left-nav
  #         - name: items
  #           label: Items
  #           widget: list
  #           fields:
  #             - { name: category, label: Category, widget: string }
  #             - { name: path, label: Path, widget: string }
  #             - name: subitems
  #               label: SubItems
  #               widget: list
  #               fields:
  #                 [
  #                   { name: subitem, label: SubItem, widget: string },
  #                   { name: path, label: Path, widget: string },
  #                 ]
  #     - name: right-nav
  #       label: Right Navigation Bar
  #       file: src/settings/right-nav.md
  #       fields:
  #         - name: key
  #           label: key
  #           widget: hidden
  #           default: right-nav
  #         - name: items
  #           label: Items
  #           widget: list
  #           fields:
  #             - { name: category, label: Category, widget: string }
  #             - { name: path, label: Path, widget: string }
  #     - name: social-links
  #       label: Social Links
  #       file: src/settings/social-links.md
  #       fields:
  #         - name: key
  #           label: key
  #           widget: hidden
  #           default: social-links
  #         - name: links
  #           label: Social Links
  #           widget: list
  #           fields:
  #             - {
  #                 name: icon,
  #                 label: Icon,
  #                 widget: select,
  #                 options: [Facebook, Instagram, LinkedIn, Twitter],
  #               }
  #             - { name: link, label: Link, widget: string }
  #     - name: footer
  #       label: Footer
  #       file: src/settings/footer.md
  #       fields:
  #         - name: key
  #           label: key
  #           widget: hidden
  #           default: footer
  #         - {
  #             name: bold_left_statement,
  #             label: Bold Left Statement,
  #             widget: string,
  #           }
  #         - name: middle_statement
  #           label: Middle Statement
  #           widget: object
  #           fields:
  #             - { name: img, label: Image, widget: image }
  #             - { name: text, label: Text, widget: string }
  # - name: projects
  #   label: Projects
  #   folder: src/pages/projects
  #   create: true
  #   delete: true
  #   slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
  #   fields:
  #     - { name: title, label: Title, widget: string }
  #     - {
  #         name: type,
  #         label: Type,
  #         widget: select,
  #         options: ['Art', 'Engagement', 'Consulting', 'Special Project'],
  #         multiple: true,
  #       }
  #     - { name: description, label: Description, widget: markdown }
  # - name: art-project
  #   label: Art Project
  #   folder: src/pages/projects
  #   filter: { field: type, value: Art }
  #   create: true
  #   delete: true
  #   slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
  #   fields:
  #     - { name: title, label: Title, widget: string }
  #     - { name: type, label: Type, widget: hidden, default: Art }
  #     - { name: description, label: Description, widget: markdown }
  # - name: engagement-project
  #   label: Engagement
  #   folder: src/pages/projects
  #   filter: { field: type, value: Engagement }
  #   create: true
  #   delete: true
  #   slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
  #   fields:
  #     - { name: title, label: Title, widget: string }
  #     - { name: type, label: Type, widget: hidden, default: Engagement }
  #     - { name: description, label: Description, widget: markdown }
  # - name: consulting-project
  #   label: Consulting Project
  #   folder: src/pages/projects
  #   filter: { field: type, value: Consulting }
  #   create: true
  #   delete: true
  #   slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
  #   fields:
  #     - { name: title, label: Title, widget: string }
  #     - { name: type, label: Type, widget: hidden, default: Consulting }
  #     - { name: description, label: Description, widget: markdown }
  # - name: special-project
  #   label: Special Project
  #   folder: src/pages/projects
  #   filter: { field: type, value: Special Project }
  #   create: true
  #   delete: true
  #   slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
  #   fields:
  #     - { name: title, label: Title, widget: string }
  #     - { name: type, label: Type, widget: hidden, default: Special Project }
  #     - { name: description, label: Description, widget: markdown }
