backend:
  name: github
  repo: kbaig/alexander-golob

media_folder: static/assets
public_folder: assets

collections:
  - name: uniquePages
    label: Unique Pages
    delete: false
    files:
      - label: Home
        name: home
        file: src/pages/index.md
        fields:
          - { name: title, label: Title, widget: string, required: false }
          - {
              name: description,
              label: Description,
              widget: string,
              required: false,
            }
          - {
              name: ogImage,
              label: Social Image,
              widget: image,
              required: false,
            }
          - name: carouselImages
            label: Carousel Image
            widget: list
            fields:
              - { name: image, label: Image, widget: image }
              - { name: description, label: Description, widget: string }
              - name: link
                label: Link
                widget: object
                fields:
                  - { name: external, label: External, widget: boolean }
                  - { name: path, label: Path, widget: string }
          - { name: heroStatement, label: Hero Statement, widget: string }
          - name: CTAs
            label: CTAs
            widget: object
            fields:
              - name: leftCTA
                label: Left CTA
                widget: object
                fields:
                  - { name: content, label: content, widget: string }
                  - { name: external, label: External, widget: boolean }
                  - { name: path, label: Path, widget: string }
              - name: rightCTA
                label: Right CTA
                widget: object
                fields:
                  - { name: content, label: content, widget: string }
                  - { name: external, label: External, widget: boolean }
                  - { name: path, label: Path, widget: string }
              - name: offCenterCTA
                label: Off Center CTA
                widget: object
                fields:
                  - { name: content, label: content, widget: string }
                  - { name: external, label: External, widget: boolean }
                  - { name: path, label: Path, widget: string }

      - label: About
        name: about
        file: src/pages/about.md
        fields:
          - { name: title, label: Title, widget: string, required: false }
          - {
              name: description,
              label: Description,
              widget: string,
              required: false,
            }
          - {
              name: ogImage,
              label: Social Image,
              required: false,
              widget: image,
            }
          - { name: heading, label: Heading, widget: string }
          - name: links
            Label: Links
            widget: list
            fields:
              - { name: content, label: Content, widget: string }
              - { name: path, label: Path, widget: string }
          - name: companyDescription
            label: Company Description
            widget: object
            fields:
              - { name: heading, label: Heading, widget: string }
              - { name: md_content, label: Content, widget: markdown }
          - name: teamSection
            label: Team Section
            widget: list
            fields:
              - { name: heading, label: Heading, widget: string }
              - name: CVLink
                label: CV Link
                widget: object
                fields:
                  - { name: show, label: Show, widget: boolean, default: false }
                  - { name: content, label: Content, widget: string }
                  - { name: external, label: External, widget: boolean }
                  - { name: path, label: Path, widget: string }
              - { name: image, label: Image, widget: image }
              - { name: contentHeading, label: Content Heading, widget: string }
              - { name: md_content, label: Content, widget: markdown }

      - label: Portfolio
        name: portfolio
        file: src/pages/portfolio.md
        fields:
          - { name: title, label: Title, widget: string, required: false }
          - {
              name: description,
              label: Description,
              widget: string,
              required: false,
            }
          - {
              name: ogImage,
              label: Social Image,
              required: false,
              widget: image,
            }
          - { name: heading, label: Heading, widget: string }

      - label: Blog
        name: blog
        file: src/pages/blog.md
        fields:
          - { name: title, label: Title, widget: string, required: false }
          - {
              name: description,
              label: Description,
              widget: string,
              required: false,
            }
          - {
              name: ogImage,
              label: Social Image,
              required: false,
              widget: image,
            }
          - { name: heading, label: Heading, widget: string }
          - name: links
            Label: Links
            widget: list
            fields:
              - { name: content, label: Content, widget: string }
              - { name: path, label: Path, widget: string }

      - label: Tags
        name: tags
        file: src/pages/tags.md
        fields:
          - { name: title, label: Title, widget: string, required: false }
          - {
              name: description,
              label: Description,
              widget: string,
              required: false,
            }
          - {
              name: ogImage,
              label: Social Image,
              required: false,
              widget: image,
            }

      - label: CV
        name: cv
        file: src/pages/cv.md
        fields:
          - { name: title, label: Title, widget: string, required: false }
          - {
              name: description,
              label: Description,
              widget: string,
              required: false,
            }
          - {
              name: ogImage,
              label: Social Image,
              required: false,
              widget: image,
            }
          - { name: heading, label: Heading, widget: string }
          - name: links
            Label: Links
            widget: list
            fields:
              - { name: content, label: Content, widget: string }
              - { name: path, label: Path, widget: string }
          - name: CVButton
            label: CV Button
            widget: object
            fields:
              - { name: content, label: Content, widget: string }
              - {
                  name: filename,
                  label: File,
                  widget: file,
                  allow_multiple: false,
                }
          - name: CV
            label: CV
            widget: object
            fields:
              - { name: title, label: Title, widget: string }
              - { name: name, label: Name, widget: string }
              - name: personalDetails
                label: Personal Details
                widget: list
                field: { name: detail, label: Detail, widget: string }
              - { name: image, label: Image, widget: image }
              - name: sections
                label: Sections
                widget: list
                fields:
                  - { name: title, label: Title, widget: string }
                  - name: items
                    label: Items
                    widget: list
                    fields:
                      - { name: year, label: Year, widget: string }
                      - name: bulletPoints
                        label: Bullet Points
                        widget: list
                        field:
                          {
                            name: bulletPoint,
                            label: Bullet Point,
                            widget: string,
                          }

      - label: Contact
        name: contact
        file: src/pages/contact.md
        fields:
          - { name: title, label: Title, widget: string, required: false }
          - {
              name: description,
              label: Description,
              widget: string,
              required: false,
            }
          - {
              name: ogImage,
              label: Social Image,
              required: false,
              widget: image,
            }
          - { name: heading, label: Heading, widget: string }
          - name: links
            Label: Links
            widget: list
            fields:
              - { name: content, label: Content, widget: string }
              - { name: path, label: Path, widget: string }
          - { name: statement, label: Statement, widget: string }
          - { name: image, label: Image, widget: image }

      - label: Subscribe
        name: subscribe
        file: src/pages/subscribe.md
        fields:
          - { name: title, label: Title, widget: string, required: false }
          - {
              name: description,
              label: Description,
              widget: string,
              required: false,
            }
          - {
              name: ogImage,
              label: Social Image,
              required: false,
              widget: image,
            }
          - { name: heading, label: Heading, widget: string }
          - name: links
            Label: Links
            widget: list
            fields:
              - { name: content, label: Content, widget: string }
              - { name: path, label: Path, widget: string }
          - { name: statement, label: Statement, widget: string }
          - { name: image, label: Image, widget: image }

      - label: '404'
        name: '404'
        file: src/pages/404.md
        fields:
          - { name: title, label: Title, widget: string, required: false }
          - {
              name: description,
              label: Description,
              widget: string,
              required: false,
            }
          - {
              name: ogImage,
              label: Social Image,
              required: false,
              widget: image,
            }
          - { name: message, label: Message, widget: string }
          - { name: subtitle, label: Subtitle, widget: string }
          - { name: preImage, label: Pre Image Statement, widget: string }
          - { name: image, label: Image, widget: image }
          - { name: preLink, label: Pre Link Statement, widget: string }
          - { name: preContact, label: Pre Contact Statement, widget: string }

  - name: blog
    label: Blog
    folder: src/pages/blog
    fields:
      - { name: templateKey, widget: hidden, default: blog-post }
      - { name: title, label: Title, widget: string, required: true }
      - { name: subtitle, label: Subtitle, widget: string, required: false }
      - {
          name: description,
          label: Description,
          widget: string,
          required: false,
        }
      - { name: ogImage, label: Social Image, required: false, widget: image }
      - { name: date, label: Date, widget: date }
      - { name: headerImage, label: Header Image, widget: image }
      - { name: author, label: Author, widget: string }
      - { name: path, label: Path, widget: string }
      - { name: tags, label: Tags, widget: list }
      - { name: body, label: body, widget: markdown }

  - name: projectCategories
    label: Project Categories
    folder: src/pages/project-categories
    fields:
      - { name: templateKey, widget: hidden, default: project-category }
      - { name: title, label: Title, widget: string, required: true }
      - {
          name: description,
          label: Description,
          widget: string,
          required: false,
        }
      - { name: ogImage, label: Social Image, required: false, widget: image }
      - { name: path, label: Path, widget: string }
      - { name: hero, label: Hero, widget: string }
      - name: subcategorySections
        label: Subcategory Sections
        widget: list
        fields:
          - { name: subcategory, label: Subcategory, widget: string }
          - { name: md_description, label: Description, widget: markdown }
          - { name: linkContent, label: Link Content, widget: string }
          - { name: image, label: Image, widget: image }

  - name: projectSubategories
    label: Project Subcategories
    folder: src/pages/project-subcategories
    fields:
      - { name: templateKey, widget: hidden, default: project-subcategory }
      - { name: title, label: Title, widget: string, required: true }
      - {
          name: description,
          label: Description,
          widget: string,
          required: false,
        }
      - { name: ogImage, label: Social Image, required: false, widget: image }
      - { name: path, label: Path, widget: string }
      - { name: category, label: Category, widget: string }
      - { name: hero, label: Hero, widget: string }
      - name: CTA
        label: CTA
        widget: object
        fields:
          - { name: path, label: Path, widget: string }
          - { name: statement, label: Statement, widget: string }
          - { name: statementAbove, label: Statement Above, widget: string }
      - { name: body, label: body, widget: markdown }

  - name: projects
    label: Projects
    folder: src/pages/projects
    fields:
      - { name: templateKey, widget: hidden, default: project-page }
      - { name: title, label: Title, widget: string, required: true }
      - {
          name: description,
          label: Description,
          widget: string,
          required: false,
        }
      - { name: ogImage, label: Social Image, required: false, widget: image }
      - { name: date, label: Date, widget: date }
      - { name: path, label: Path, widget: string }
      - { name: category, label: Category, widget: string }
      - { name: subcategories, label: Subcategories, widget: list }
      - {
          name: isFeatured,
          label: Featured Post,
          widget: boolean,
          default: false,
        }
      - name: details
        label: Details
        widget: list
        fields:
          - { name: attribute, label: Attribute, widget: string }
          - { name: value, label: Value, widget: string }
      - name: descriptions
        label: Descriptions
        widget: list
        fields:
          - {
              name: startingRow,
              label: Starting Row,
              widget: number,
              valueType: int,
            }
          - { name: md_content, label: Content, widget: markdown }
      - name: images
        label: Images
        widget: list
        field: { name: image, label: Image, widget: image }

  - name: siteSettings
    label: Site Settings
    delete: false
    files:
      - name: logo
        label: Logo
        file: src/site-settings/logo.md
        fields:
          - { name: logo, label: Logo, widget: image }

      - name: SEO
        label: SEO
        file: src/site-settings/SEO.md
        fields:
          - { name: siteTitle, label: Site Title, widget: string }
          - { name: siteDescription, label: Site Description, widget: string }

  - name: sharedComponents
    label: Shared Components
    delete: false
    files:
      - name: socialLinks
        label: Social Links
        file: src/shared-components/social-links.md
        fields:
          - name: links
            label: Links
            widget: list
            fields:
              - {
                  name: icon,
                  label: Icon,
                  widget: select,
                  options: [Facebook, Instagram, Twitter, LinkedIn],
                }
              - { name: link, label: Link, widget: string }

      - name: footer
        label: Footer
        file: src/shared-components/footer.md
        fields:
          - {
              name: boldLeftStatement,
              label: Bold Left Statement,
              widget: string,
            }
          - name: middleStatement
            label: Middle Statement
            widget: object
            fields:
              - { name: img, label: Image, widget: image }
              - { name: text, label: Text, widget: string }

      - name: leftNav
        label: Left Nav
        file: src/shared-components/left-nav.md
        fields:
          - name: homeLogo
            label: Home Logo
            widget: object
            fields:
              - { name: logo, label: Logo, widget: image }
              - { name: text, label: Text, widget: string }
          - name: items
            label: Items
            widget: list
            fields:
              - { name: category, label: Category, widget: string }
              - { name: path, label: Path, widget: string }
              - name: subitems
                label: Subitems
                widget: list
                fields:
                  - { name: subitem, label: Subitem, widget: string }
                  - { name: path, label: Path, widget: string }

      - name: rightNav
        label: Right Nav
        file: src/shared-components/right-nav.md
        fields:
          - { name: secondaryLogo, label: Secondary Logo, widget: image }
          - name: items
            label: Items
            widget: list
            fields:
              - { name: category, label: Category, widget: string }
              - { name: path, label: Path, widget: string }

      - name: finalCta
        label: Final CTA
        file: src/shared-components/final-cta.md
        fields:
          - { name: content, label: Content, widget: string }
          - { name: external, label: External, widget: boolean }
          - { name: path, label: Path, widget: string }

      - name: supportCTA
        label: Support CTA
        file: src/shared-components/support-cta.md
        fields:
          - { name: outerContent, label: Outer Content, widget: string }
          - name: link
            label: Link
            widget: object
            fields:
              - { name: content, label: Content, widget: string }
              - { name: external, label: External, widget: boolean }
              - { name: path, label: Path, widget: string }
