backend:
  name: github
  repo: kbaig/alexander-golob
  # name: test-repo

media_folder: static/assets
public_folder: assets

collections:
  - name: unique-pages
    label: Unique Pages
    create: false
    delete: false
    files:
      - label: Home
        name: home
        file: src/pages/index.md
        fields:
          - name: carouselImages
            label: Carousel Image
            widget: list
            fields:
              - { name: image, label: Image, widget: image }
              - { name: description, label: Description, widget: string }
          - { name: heroStatement, label: Hero Statement, widget: string }
          - name: leftCta
            label: Left CTA
            widget: object
            fields:
              - { name: content, label: Content, widget: string }
              - { name: path, label: Path, widget: string }
          - name: rightCta
            label: Right CTA
            widget: object
            fields:
              - { name: content, label: Content, widget: string }
              - { name: path, label: Path, widget: string }
      - name: about
        label: About
        file: src/pages/about/index.md
        fields:
          - { name: heading, label: Heading, widget: string }
          - name: subheadings
            label: Subheading
            widget: object
            fields:
              - { name: subheading1, label: Subheading 1, widget: string }
              - { name: subheading2, label: Subheading 2, widget: string }
              - { name: subheading3, label: Subheading 3, widget: string }
              - { name: subheading4, label: Subheading 4, widget: string }
          - name: descriptions
            label: Descriptions
            widget: object
            fields:
              - name: description1
                label: Description 1
                widget: object
                fields:
                  - { name: heading, label: Heading, widget: string }
                  - { name: content, label: Content, widget: markdown }
                  - { name: image, label: Image, widget: image }
              - name: description2
                label: Description 2
                widget: object
                fields:
                  - { name: heading, label: Heading, widget: string }
                  - { name: content, label: Content, widget: markdown }
                  - { name: image, label: Image, widget: image }
              - name: description3
                label: Description 3
                widget: object
                fields:
                  - { name: heading, label: Heading, widget: string }
                  - { name: content, label: Content, widget: markdown }
                  - { name: image, label: Image, widget: image }

  - name: project-subcategories
    label: Project Subcategories
    folder: src/pages/project-categories-and-subcategories
    filter: { field: templateKey, value: project-subcategory }
    create: true
    delete: true
    fields:
      - { name: templateKey, widget: hidden, default: project-subcategory }
      - { name: title, label: Name, widget: string }
      - name: category
        label: Category
        widget: select
        options:
          - { label: Art, value: art }
          - { label: Engagements, value: engagements }
          - { label: Consulting, value: consulting }
          - { label: Special Projects, value: specialProjects }
      - { name: descriptionHeading, label: Description Heading, widget: string }
      - { name: body, label: Description Body, widget: markdown }
      - name: cta
        label: CTA
        widget: object
        fields:
          - { name: statementAbove, label: Statement Above CTA, widget: string }
          - { name: statement, label: CTA Statement, widget: string }
          - { name: path, label: Path, widget: string }
  # - name: settings
  #   label: Site Settings
  #   files:
  #     - name: left-nav
  #       label: Left Navigation Bar
  #       file: src/settings/left-nav.md
  #       fields:
  #         - name: key
  #           label: key
  #           widget: hidden
  #           default: left-nav
  #         - name: items
  #           label: Items
  #           widget: list
  #           fields:
  #             - { name: category, label: Category, widget: string }
  #             - { name: path, label: Path, widget: string }
  #             - name: subitems
  #               label: SubItems
  #               widget: list
  #               fields:
  #                 [
  #                   { name: subitem, label: SubItem, widget: string },
  #                   { name: path, label: Path, widget: string },
  #                 ]
  #     - name: right-nav
  #       label: Right Navigation Bar
  #       file: src/settings/right-nav.md
  #       fields:
  #         - name: key
  #           label: key
  #           widget: hidden
  #           default: right-nav
  #         - name: items
  #           label: Items
  #           widget: list
  #           fields:
  #             - { name: category, label: Category, widget: string }
  #             - { name: path, label: Path, widget: string }
  #     - name: social-links
  #       label: Social Links
  #       file: src/settings/social-links.md
  #       fields:
  #         - name: key
  #           label: key
  #           widget: hidden
  #           default: social-links
  #         - name: links
  #           label: Social Links
  #           widget: list
  #           fields:
  #             - {
  #                 name: icon,
  #                 label: Icon,
  #                 widget: select,
  #                 options: [Facebook, Instagram, LinkedIn, Twitter],
  #               }
  #             - { name: link, label: Link, widget: string }
  #     - name: footer
  #       label: Footer
  #       file: src/settings/footer.md
  #       fields:
  #         - name: key
  #           label: key
  #           widget: hidden
  #           default: footer
  #         - {
  #             name: bold_left_statement,
  #             label: Bold Left Statement,
  #             widget: string,
  #           }
  #         - name: middle_statement
  #           label: Middle Statement
  #           widget: object
  #           fields:
  #             - { name: img, label: Image, widget: image }
  #             - { name: text, label: Text, widget: string }
  # - name: projects
  #   label: Projects
  #   folder: src/pages/projects
  #   create: true
  #   delete: true
  #   slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
  #   fields:
  #     - { name: title, label: Title, widget: string }
  #     - {
  #         name: type,
  #         label: Type,
  #         widget: select,
  #         options: ['Art', 'Engagement', 'Consulting', 'Special Project'],
  #         multiple: true,
  #       }
  #     - { name: description, label: Description, widget: markdown }
  # - name: art-project
  #   label: Art Project
  #   folder: src/pages/projects
  #   filter: { field: type, value: Art }
  #   create: true
  #   delete: true
  #   slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
  #   fields:
  #     - { name: title, label: Title, widget: string }
  #     - { name: type, label: Type, widget: hidden, default: Art }
  #     - { name: description, label: Description, widget: markdown }
  # - name: engagement-project
  #   label: Engagement
  #   folder: src/pages/projects
  #   filter: { field: type, value: Engagement }
  #   create: true
  #   delete: true
  #   slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
  #   fields:
  #     - { name: title, label: Title, widget: string }
  #     - { name: type, label: Type, widget: hidden, default: Engagement }
  #     - { name: description, label: Description, widget: markdown }
  # - name: consulting-project
  #   label: Consulting Project
  #   folder: src/pages/projects
  #   filter: { field: type, value: Consulting }
  #   create: true
  #   delete: true
  #   slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
  #   fields:
  #     - { name: title, label: Title, widget: string }
  #     - { name: type, label: Type, widget: hidden, default: Consulting }
  #     - { name: description, label: Description, widget: markdown }
  # - name: special-project
  #   label: Special Project
  #   folder: src/pages/projects
  #   filter: { field: type, value: Special Project }
  #   create: true
  #   delete: true
  #   slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
  #   fields:
  #     - { name: title, label: Title, widget: string }
  #     - { name: type, label: Type, widget: hidden, default: Special Project }
  #     - { name: description, label: Description, widget: markdown }
