backend:
  name: github
  repo: kbaig/alexander-golob
  # name: test-repo

media_folder: static/assets
public_folder: assets

collections:
  - name: artwork
    label: Artwork
    folder: src/pages/artwork
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - { name: image, label: Image, widget: image }
      - { name: creation_date, label: Created in, widget: number }
      - { name: body, label: Description, widget: markdown }
