backend:
  name: github
  repo: kbaig/alexander-golob
  # name: test-repo

media_folder: static/assets
public_folder: assets

collections:
  - name: pages
    label: Pages
    files:
      - label: Home Page
        name: home-page
        file: src/pages/content/index.md
        fields:
          - name: logo
            label: Logo
            widget: object
            fields:
              - { name: image, label: Image, widget: image }
              - { name: text, label: Text, widget: string }
          - {
              name: secondary-nav-logo,
              label: Secondary Nav Logo,
              widget: image,
            }
          - name: carousel-images
            label: Carousel Image
            widget: list
            fields:
              - { name: image, label: Image, widget: image }
              - { name: description, label: Description, widget: string }
          - { name: hero-statement, label: Hero Statement, widget: string }
          - name: left-cta
            label: Left CTA
            widget: object
            fields:
              - { name: content, label: Content, widget: string }
              - { name: path, label: Path, widget: string }
          - name: right-cta
            label: Right CTA
            widget: object
            fields:
              - { name: content, label: Content, widget: string }
              - { name: path, label: Path, widget: string }

  - name: settings
    label: Site Settings
    files:
      - name: left-nav
        label: Left Navigation Bar
        file: src/settings/left-nav.md
        fields:
          - name: items
            label: Items
            widget: list
            fields:
              - { name: category, label: Category, widget: string }
              - { name: path, label: Path, widget: string }
              - name: subitems
                label: SubItems
                widget: list
                fields:
                  [
                    { name: subitem, label: SubItem, widget: string },
                    { name: path, label: Path, widget: string },
                  ]
      - name: right-nav
        label: Right Navigation Bar
        file: src/settings/right-nav.md
        fields:
          - name: items
            label: Items
            widget: list
            fields:
              - { name: category, label: Category, widget: string }
              - { name: path, label: Path, widget: string }

  - name: projects
    label: Projects
    folder: src/pages/projects
    create: true
    delete: true
    slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
    fields:
      - { name: title, label: Title, widget: string }
      - {
          name: type,
          label: Type,
          widget: select,
          options: ['Art', 'Engagement', 'Consulting', 'Special Project'],
          multiple: true,
        }
      - { name: description, label: Description, widget: markdown }

  - name: art-project
    label: Art Project
    folder: src/pages/projects
    filter: { field: type, value: Art }
    create: true
    delete: true
    slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
    fields:
      - { name: title, label: Title, widget: string }
      - { name: type, label: Type, widget: hidden, default: Art }
      - { name: description, label: Description, widget: markdown }

  - name: engagement-project
    label: Engagement
    folder: src/pages/projects
    filter: { field: type, value: Engagement }
    create: true
    delete: true
    slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
    fields:
      - { name: title, label: Title, widget: string }
      - { name: type, label: Type, widget: hidden, default: Engagement }
      - { name: description, label: Description, widget: markdown }

  - name: consulting-project
    label: Consulting Project
    folder: src/pages/projects
    filter: { field: type, value: Consulting }
    create: true
    delete: true
    slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
    fields:
      - { name: title, label: Title, widget: string }
      - { name: type, label: Type, widget: hidden, default: Consulting }
      - { name: description, label: Description, widget: markdown }

  - name: special-project
    label: Special Project
    folder: src/pages/projects
    filter: { field: type, value: Special Project }
    create: true
    delete: true
    slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
    fields:
      - { name: title, label: Title, widget: string }
      - { name: type, label: Type, widget: hidden, default: Special Project }
      - { name: description, label: Description, widget: markdown }
