backend:
  name: github
  repo: kbaig/alexander-golob
  # name: test-repo

media_folder: static/assets
public_folder: assets

collections:
  - name: pages
    label: Pages
    files:
      - label: Home Page
        name: home-page
        file: src/pages/content/index.md
        fields:
          - name: logo
            label: Logo
            widget: object
            fields:
              - { name: image, label: Image, widget: image }
              - { name: text, label: Text, widget: string }
          - {
              name: secondary-nav-logo,
              label: Secondary Nav Logo,
              widget: image,
            }
          - name: carousel-images
            label: Carousel Image
            widget: list
            fields:
              - { name: image, label: Image, widget: image }
              - { name: description, label: Description, widget: string }
          - { name: hero-statement, label: Hero Statement, widget: string }
          - name: left-cta
            label: Left CTA
            widget: object
            fields:
              - { name: content, label: Content, widget: string }
              - { name: path, label: Path, widget: string }
          - name: right-cta
            label: Right CTA
            widget: object
            fields:
              - { name: content, label: Content, widget: string }
              - { name: path, label: Path, widget: string }

  - name: artwork
    label: Artwork
    folder: src/pages/artwork
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - { name: image, label: Image, widget: image }
      - { name: creation_date, label: Created in, widget: number }
      - { name: body, label: Description, widget: markdown }
